### PR TITLE
Update WalleePaymentHandler.php Bug!!!

### PR DESCRIPTION
**Pull request by oriske**

### CODE REVIEW

**Comment by vttn** [comment]
@oriske thank you for the patch.

Currently we handle the paid status via webhooks https://github.com/wallee-payment/shopware-6/blob/master/src/Core/Api/WebHooks/Controller/WebHookController.php

**Comment by oriske** [comment]
Which is not working!

herzliche Grüsse 

Oliver Riske
----------------------------------------------
Next AG
Oliver Riske

Scheffelstrasse 1
CH-9000 St.Gallen
***@***.***
www.nextag.ch

+41 71 242 11 11 tel
+41 71 242 11 22 fax



   Victor Ndambakuwa --- Re: [wallee-payment/shopware-6] Update WalleePaymentHandler.php Bug!!! (#1) --- 
    Von:"Victor Ndambakuwa" ***@***.***>An:"wallee-payment/shopware-6" ***@***.***>Kopie:"Oliver Riske" ***@***.***>, "Mention" ***@***.***>Datum:Mo. 15.03.2021 08:01Betreff:Re: [wallee-payment/shopware-6] Update WalleePaymentHandler.php Bug!!! (#1)
  
  @oriske thank you for the patch. Currently we handle the paid status via webhooks https://github.com/wallee-payment/shopware-6/blob/master/src/Core/Api/WebHooks/Controller/WebHookController.php —

**Comment by vttn** [comment]
@oriske 

Please open a ticket with support so that we can address your issue in a proper forum.

https://support.wallee.com/hc/en-us

Regards,

@vttn

**Comment by oriske** [comment]
You can forward your Problem - mot me!
I will escalate your response now.
 
herzliche Grüsse 

Oliver Riske
----------------------------------------------
Next AG
Oliver Riske

Scheffelstrasse 1
CH-9000 St.Gallen
***@***.***
www.nextag.ch

+41 71 242 11 11 tel



Von:    "Victor Ndambakuwa" ***@***.***>
An:     "wallee-payment/shopware-6" ***@***.***>
Kopie:  "Oliver Riske" ***@***.***>, "Mention" 
***@***.***>
Datum:  15.03.2021 08:05
Betreff:        Re: [wallee-payment/shopware-6] Update 
WalleePaymentHandler.php Bug!!! (#1)



@oriske
Please open a ticket with support so that we can address your issue in a 
proper forum.
https://support.wallee.com/hc/en-us
Regards,
@vttn

**Pull request closed without merging**
